ALTER TABLE dashboard_widgets
  ADD COLUMN IF NOT EXISTS col_start INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS row_start INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS col_span INTEGER DEFAULT 6,
  ADD COLUMN IF NOT EXISTS row_span INTEGER DEFAULT 1;
